import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>)
  {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}

// export default function RootLayout({ children }: { children: React.ReactNode }) {
//   // State untuk status login
//   const [isLoggedIn, setIsLoggedIn] = useState(false);

//   useEffect(() => {
//     // Cek apakah pengguna sudah login berdasarkan localStorage
//     const token = localStorage.getItem('sessionToken');
//     setIsLoggedIn(!!token); // Jika token ada, berarti sudah login
//   }, []);

//   return (
//     <html lang="en">
//       <head />
//       <body>
//         <NavBar isLoggedIn={isLoggedIn} setIsLoggedIn={setIsLoggedIn} />
//         <main>{children}</main>
//       </body>
//     </html>
//   );
// }
